In [1]:
from keras.applications.vgg16 import VGG16
model = VGG16()

Using TensorFlow backend.


In [2]:
print(model.summary())

Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0     

In [4]:
from keras.utils.vis_utils import plot_model
plot_model(model, to_file='vgg.png')

OSError: `pydot` failed to call GraphViz.Please install GraphViz (https://www.graphviz.org/) and ensure that its executables are in the $PATH.

In [3]:
from keras.preprocessing.image import load_img
image = load_img('coffee.jpg', target_size=(224, 224))

In [5]:
print(image)
from keras.preprocessing.image import img_to_array
image = img_to_array(image)

<PIL.Image.Image image mode=RGB size=224x224 at 0x1DC199A01D0>


In [6]:
print(image)

[[[ 64.  54.   3.]
  [ 64.  57.   3.]
  [ 78.  53.   0.]
  ...
  [117.  91.  64.]
  [111.  88.  44.]
  [107.  81.  64.]]

 [[ 73.  49.   5.]
  [ 66.  57.   0.]
  [ 62.  54.   8.]
  ...
  [118.  90.  53.]
  [122.  92.  56.]
  [ 95.  64.  35.]]

 [[ 67.  56.   2.]
  [ 71.  52.  10.]
  [ 71.  55.   0.]
  ...
  [120.  90.  66.]
  [127.  99.  62.]
  [104.  74.  46.]]

 ...

 [[ 40.  47.  57.]
  [ 48.  43.  66.]
  [ 48.  54.  52.]
  ...
  [ 36.  42.  32.]
  [ 50.  47.  38.]
  [ 50.  43.  35.]]

 [[ 45.  43.  57.]
  [ 49.  49.  57.]
  [ 43.  46.  55.]
  ...
  [ 28.  48.  36.]
  [ 48.  40.  37.]
  [ 56.  49.  43.]]

 [[ 45.  42.  59.]
  [ 47.  48.  53.]
  [ 57.  42.  65.]
  ...
  [ 53.  34.  38.]
  [ 38.  44.  34.]
  [ 45.  42.  35.]]]


In [7]:
image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))

In [8]:
from keras.applications.vgg16 import preprocess_input
image = preprocess_input(image)

In [9]:
yhat = model.predict(image)

In [10]:
from keras.applications.vgg16 import decode_predictions
# convert the probabilities to class labels
label = decode_predictions(yhat)
# retrieve the most likely result, e.g. highest probability
label = label[0][0]
# print the classification
print('%s (%.2f%%)' % (label[1], label[2]*100))

coffee_mug (75.27%)
